/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LandingRouteImport } from './routes/_landing/route'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/_auth/route'
import { Route as ExamIndexImport } from './routes/exam/index'
import { Route as PlacementIdIndexImport } from './routes/placement/$id/index'
import { Route as ExamIdIndexImport } from './routes/exam/$id/index'
import { Route as AuthenticatedOnlineIndexImport } from './routes/_authenticated/online/index'
import { Route as AuthenticatedBookingsIndexImport } from './routes/_authenticated/bookings/index'
import { Route as ExamOnlineIdIndexImport } from './routes/exam/online/$id/index'
import { Route as ExamAdminIdIndexImport } from './routes/exam/admin/$id/index'
import { Route as LandingExamsOnlineIndexImport } from './routes/_landing/exams/online/index'

// Create Virtual Routes

const PlacementIndexLazyImport = createFileRoute('/placement/')()
const LandingIndexLazyImport = createFileRoute('/_landing/')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const ExamEndIndexLazyImport = createFileRoute('/exam/end/')()
const LandingExamsIndexLazyImport = createFileRoute('/_landing/exams/')()
const AuthenticatedTransactionsIndexLazyImport = createFileRoute(
  '/_authenticated/transactions/',
)()
const AuthenticatedProfileIndexLazyImport = createFileRoute(
  '/_authenticated/profile/',
)()
const AuthRegisterIndexLazyImport = createFileRoute('/_auth/register/')()
const AuthLoginIndexLazyImport = createFileRoute('/_auth/login/')()
const AuthForgotPasswordIndexLazyImport = createFileRoute(
  '/_auth/forgot-password/',
)()
const LandingExamsIdIndexLazyImport = createFileRoute('/_landing/exams/$id/')()
const AuthenticatedOnlineIdIndexLazyImport = createFileRoute(
  '/_authenticated/online/$id/',
)()
const AuthenticatedBookingsIdIndexLazyImport = createFileRoute(
  '/_authenticated/bookings/$id/',
)()

// Create/Update Routes

const LandingRouteRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const PlacementIndexLazyRoute = PlacementIndexLazyImport.update({
  id: '/placement/',
  path: '/placement/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/placement/index.lazy').then((d) => d.Route),
)

const LandingIndexLazyRoute = LandingIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRouteRoute,
} as any).lazy(() =>
  import('./routes/_landing/index.lazy').then((d) => d.Route),
)

const ExamIndexRoute = ExamIndexImport.update({
  id: '/exam/',
  path: '/exam/',
  getParentRoute: () => rootRoute,
} as any)

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const ExamEndIndexLazyRoute = ExamEndIndexLazyImport.update({
  id: '/exam/end/',
  path: '/exam/end/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exam/end/index.lazy').then((d) => d.Route),
)

const LandingExamsIndexLazyRoute = LandingExamsIndexLazyImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => LandingRouteRoute,
} as any).lazy(() =>
  import('./routes/_landing/exams/index.lazy').then((d) => d.Route),
)

const AuthenticatedTransactionsIndexLazyRoute =
  AuthenticatedTransactionsIndexLazyImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/transactions/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedProfileIndexLazyRoute =
  AuthenticatedProfileIndexLazyImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/profile/index.lazy').then((d) => d.Route),
  )

const AuthRegisterIndexLazyRoute = AuthRegisterIndexLazyImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/register/index.lazy').then((d) => d.Route),
)

const AuthLoginIndexLazyRoute = AuthLoginIndexLazyImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_auth/login/index.lazy').then((d) => d.Route),
)

const AuthForgotPasswordIndexLazyRoute =
  AuthForgotPasswordIndexLazyImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => AuthRouteRoute,
  } as any).lazy(() =>
    import('./routes/_auth/forgot-password/index.lazy').then((d) => d.Route),
  )

const PlacementIdIndexRoute = PlacementIdIndexImport.update({
  id: '/placement/$id/',
  path: '/placement/$id/',
  getParentRoute: () => rootRoute,
} as any)

const ExamIdIndexRoute = ExamIdIndexImport.update({
  id: '/exam/$id/',
  path: '/exam/$id/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedOnlineIndexRoute = AuthenticatedOnlineIndexImport.update({
  id: '/online/',
  path: '/online/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedBookingsIndexRoute = AuthenticatedBookingsIndexImport.update(
  {
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const LandingExamsIdIndexLazyRoute = LandingExamsIdIndexLazyImport.update({
  id: '/exams/$id/',
  path: '/exams/$id/',
  getParentRoute: () => LandingRouteRoute,
} as any).lazy(() =>
  import('./routes/_landing/exams/$id/index.lazy').then((d) => d.Route),
)

const AuthenticatedOnlineIdIndexLazyRoute =
  AuthenticatedOnlineIdIndexLazyImport.update({
    id: '/online/$id/',
    path: '/online/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/online/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedBookingsIdIndexLazyRoute =
  AuthenticatedBookingsIdIndexLazyImport.update({
    id: '/bookings/$id/',
    path: '/bookings/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/bookings/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )

const ExamOnlineIdIndexRoute = ExamOnlineIdIndexImport.update({
  id: '/exam/online/$id/',
  path: '/exam/online/$id/',
  getParentRoute: () => rootRoute,
} as any)

const ExamAdminIdIndexRoute = ExamAdminIdIndexImport.update({
  id: '/exam/admin/$id/',
  path: '/exam/admin/$id/',
  getParentRoute: () => rootRoute,
} as any)

const LandingExamsOnlineIndexRoute = LandingExamsOnlineIndexImport.update({
  id: '/exams/online/',
  path: '/exams/online/',
  getParentRoute: () => LandingRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/exam/': {
      id: '/exam/'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamIndexImport
      parentRoute: typeof rootRoute
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexLazyImport
      parentRoute: typeof LandingRouteImport
    }
    '/placement/': {
      id: '/placement/'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/online/': {
      id: '/_authenticated/online/'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof AuthenticatedOnlineIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/exam/$id/': {
      id: '/exam/$id/'
      path: '/exam/$id'
      fullPath: '/exam/$id'
      preLoaderRoute: typeof ExamIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/placement/$id/': {
      id: '/placement/$id/'
      path: '/placement/$id'
      fullPath: '/placement/$id'
      preLoaderRoute: typeof PlacementIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexLazyImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexLazyImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterIndexLazyImport
      parentRoute: typeof AuthRouteImport
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_landing/exams/': {
      id: '/_landing/exams/'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof LandingExamsIndexLazyImport
      parentRoute: typeof LandingRouteImport
    }
    '/exam/end/': {
      id: '/exam/end/'
      path: '/exam/end'
      fullPath: '/exam/end'
      preLoaderRoute: typeof ExamEndIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_landing/exams/online/': {
      id: '/_landing/exams/online/'
      path: '/exams/online'
      fullPath: '/exams/online'
      preLoaderRoute: typeof LandingExamsOnlineIndexImport
      parentRoute: typeof LandingRouteImport
    }
    '/exam/admin/$id/': {
      id: '/exam/admin/$id/'
      path: '/exam/admin/$id'
      fullPath: '/exam/admin/$id'
      preLoaderRoute: typeof ExamAdminIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/exam/online/$id/': {
      id: '/exam/online/$id/'
      path: '/exam/online/$id'
      fullPath: '/exam/online/$id'
      preLoaderRoute: typeof ExamOnlineIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/bookings/$id/': {
      id: '/_authenticated/bookings/$id/'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthenticatedBookingsIdIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/online/$id/': {
      id: '/_authenticated/online/$id/'
      path: '/online/$id'
      fullPath: '/online/$id'
      preLoaderRoute: typeof AuthenticatedOnlineIdIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_landing/exams/$id/': {
      id: '/_landing/exams/$id/'
      path: '/exams/$id'
      fullPath: '/exams/$id'
      preLoaderRoute: typeof LandingExamsIdIndexLazyImport
      parentRoute: typeof LandingRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthForgotPasswordIndexLazyRoute: typeof AuthForgotPasswordIndexLazyRoute
  AuthLoginIndexLazyRoute: typeof AuthLoginIndexLazyRoute
  AuthRegisterIndexLazyRoute: typeof AuthRegisterIndexLazyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordIndexLazyRoute: AuthForgotPasswordIndexLazyRoute,
  AuthLoginIndexLazyRoute: AuthLoginIndexLazyRoute,
  AuthRegisterIndexLazyRoute: AuthRegisterIndexLazyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
  AuthenticatedOnlineIndexRoute: typeof AuthenticatedOnlineIndexRoute
  AuthenticatedProfileIndexLazyRoute: typeof AuthenticatedProfileIndexLazyRoute
  AuthenticatedTransactionsIndexLazyRoute: typeof AuthenticatedTransactionsIndexLazyRoute
  AuthenticatedBookingsIdIndexLazyRoute: typeof AuthenticatedBookingsIdIndexLazyRoute
  AuthenticatedOnlineIdIndexLazyRoute: typeof AuthenticatedOnlineIdIndexLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
  AuthenticatedOnlineIndexRoute: AuthenticatedOnlineIndexRoute,
  AuthenticatedProfileIndexLazyRoute: AuthenticatedProfileIndexLazyRoute,
  AuthenticatedTransactionsIndexLazyRoute:
    AuthenticatedTransactionsIndexLazyRoute,
  AuthenticatedBookingsIdIndexLazyRoute: AuthenticatedBookingsIdIndexLazyRoute,
  AuthenticatedOnlineIdIndexLazyRoute: AuthenticatedOnlineIdIndexLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LandingRouteRouteChildren {
  LandingIndexLazyRoute: typeof LandingIndexLazyRoute
  LandingExamsIndexLazyRoute: typeof LandingExamsIndexLazyRoute
  LandingExamsOnlineIndexRoute: typeof LandingExamsOnlineIndexRoute
  LandingExamsIdIndexLazyRoute: typeof LandingExamsIdIndexLazyRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingIndexLazyRoute: LandingIndexLazyRoute,
  LandingExamsIndexLazyRoute: LandingExamsIndexLazyRoute,
  LandingExamsOnlineIndexRoute: LandingExamsOnlineIndexRoute,
  LandingExamsIdIndexLazyRoute: LandingExamsIdIndexLazyRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof LandingRouteRouteWithChildren
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/exam': typeof ExamIndexRoute
  '/': typeof LandingIndexLazyRoute
  '/placement': typeof PlacementIndexLazyRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/online': typeof AuthenticatedOnlineIndexRoute
  '/exam/$id': typeof ExamIdIndexRoute
  '/placement/$id': typeof PlacementIdIndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexLazyRoute
  '/login': typeof AuthLoginIndexLazyRoute
  '/register': typeof AuthRegisterIndexLazyRoute
  '/profile': typeof AuthenticatedProfileIndexLazyRoute
  '/transactions': typeof AuthenticatedTransactionsIndexLazyRoute
  '/exams': typeof LandingExamsIndexLazyRoute
  '/exam/end': typeof ExamEndIndexLazyRoute
  '/exams/online': typeof LandingExamsOnlineIndexRoute
  '/exam/admin/$id': typeof ExamAdminIdIndexRoute
  '/exam/online/$id': typeof ExamOnlineIdIndexRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdIndexLazyRoute
  '/online/$id': typeof AuthenticatedOnlineIdIndexLazyRoute
  '/exams/$id': typeof LandingExamsIdIndexLazyRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/exam': typeof ExamIndexRoute
  '/': typeof LandingIndexLazyRoute
  '/placement': typeof PlacementIndexLazyRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/online': typeof AuthenticatedOnlineIndexRoute
  '/exam/$id': typeof ExamIdIndexRoute
  '/placement/$id': typeof PlacementIdIndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexLazyRoute
  '/login': typeof AuthLoginIndexLazyRoute
  '/register': typeof AuthRegisterIndexLazyRoute
  '/profile': typeof AuthenticatedProfileIndexLazyRoute
  '/transactions': typeof AuthenticatedTransactionsIndexLazyRoute
  '/exams': typeof LandingExamsIndexLazyRoute
  '/exam/end': typeof ExamEndIndexLazyRoute
  '/exams/online': typeof LandingExamsOnlineIndexRoute
  '/exam/admin/$id': typeof ExamAdminIdIndexRoute
  '/exam/online/$id': typeof ExamOnlineIdIndexRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdIndexLazyRoute
  '/online/$id': typeof AuthenticatedOnlineIdIndexLazyRoute
  '/exams/$id': typeof LandingExamsIdIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_landing': typeof LandingRouteRouteWithChildren
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/exam/': typeof ExamIndexRoute
  '/_landing/': typeof LandingIndexLazyRoute
  '/placement/': typeof PlacementIndexLazyRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/online/': typeof AuthenticatedOnlineIndexRoute
  '/exam/$id/': typeof ExamIdIndexRoute
  '/placement/$id/': typeof PlacementIdIndexRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexLazyRoute
  '/_auth/login/': typeof AuthLoginIndexLazyRoute
  '/_auth/register/': typeof AuthRegisterIndexLazyRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexLazyRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexLazyRoute
  '/_landing/exams/': typeof LandingExamsIndexLazyRoute
  '/exam/end/': typeof ExamEndIndexLazyRoute
  '/_landing/exams/online/': typeof LandingExamsOnlineIndexRoute
  '/exam/admin/$id/': typeof ExamAdminIdIndexRoute
  '/exam/online/$id/': typeof ExamOnlineIdIndexRoute
  '/_authenticated/bookings/$id/': typeof AuthenticatedBookingsIdIndexLazyRoute
  '/_authenticated/online/$id/': typeof AuthenticatedOnlineIdIndexLazyRoute
  '/_landing/exams/$id/': typeof LandingExamsIdIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/exam'
    | '/'
    | '/placement'
    | '/bookings'
    | '/online'
    | '/exam/$id'
    | '/placement/$id'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/profile'
    | '/transactions'
    | '/exams'
    | '/exam/end'
    | '/exams/online'
    | '/exam/admin/$id'
    | '/exam/online/$id'
    | '/bookings/$id'
    | '/online/$id'
    | '/exams/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/exam'
    | '/'
    | '/placement'
    | '/bookings'
    | '/online'
    | '/exam/$id'
    | '/placement/$id'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/profile'
    | '/transactions'
    | '/exams'
    | '/exam/end'
    | '/exams/online'
    | '/exam/admin/$id'
    | '/exam/online/$id'
    | '/bookings/$id'
    | '/online/$id'
    | '/exams/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_landing'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/exam/'
    | '/_landing/'
    | '/placement/'
    | '/_authenticated/bookings/'
    | '/_authenticated/online/'
    | '/exam/$id/'
    | '/placement/$id/'
    | '/_auth/forgot-password/'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_authenticated/profile/'
    | '/_authenticated/transactions/'
    | '/_landing/exams/'
    | '/exam/end/'
    | '/_landing/exams/online/'
    | '/exam/admin/$id/'
    | '/exam/online/$id/'
    | '/_authenticated/bookings/$id/'
    | '/_authenticated/online/$id/'
    | '/_landing/exams/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  ExamIndexRoute: typeof ExamIndexRoute
  PlacementIndexLazyRoute: typeof PlacementIndexLazyRoute
  ExamIdIndexRoute: typeof ExamIdIndexRoute
  PlacementIdIndexRoute: typeof PlacementIdIndexRoute
  ExamEndIndexLazyRoute: typeof ExamEndIndexLazyRoute
  ExamAdminIdIndexRoute: typeof ExamAdminIdIndexRoute
  ExamOnlineIdIndexRoute: typeof ExamOnlineIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LandingRouteRoute: LandingRouteRouteWithChildren,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  ExamIndexRoute: ExamIndexRoute,
  PlacementIndexLazyRoute: PlacementIndexLazyRoute,
  ExamIdIndexRoute: ExamIdIndexRoute,
  PlacementIdIndexRoute: PlacementIdIndexRoute,
  ExamEndIndexLazyRoute: ExamEndIndexLazyRoute,
  ExamAdminIdIndexRoute: ExamAdminIdIndexRoute,
  ExamOnlineIdIndexRoute: ExamOnlineIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_authenticated",
        "/_landing",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/exam/",
        "/placement/",
        "/exam/$id/",
        "/placement/$id/",
        "/exam/end/",
        "/exam/admin/$id/",
        "/exam/online/$id/"
      ]
    },
    "/_auth": {
      "filePath": "_auth/route.tsx",
      "children": [
        "/_auth/forgot-password/",
        "/_auth/login/",
        "/_auth/register/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/bookings/",
        "/_authenticated/online/",
        "/_authenticated/profile/",
        "/_authenticated/transactions/",
        "/_authenticated/bookings/$id/",
        "/_authenticated/online/$id/"
      ]
    },
    "/_landing": {
      "filePath": "_landing/route.tsx",
      "children": [
        "/_landing/",
        "/_landing/exams/",
        "/_landing/exams/online/",
        "/_landing/exams/$id/"
      ]
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/exam/": {
      "filePath": "exam/index.tsx"
    },
    "/_landing/": {
      "filePath": "_landing/index.lazy.tsx",
      "parent": "/_landing"
    },
    "/placement/": {
      "filePath": "placement/index.lazy.tsx"
    },
    "/_authenticated/bookings/": {
      "filePath": "_authenticated/bookings/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/online/": {
      "filePath": "_authenticated/online/index.tsx",
      "parent": "/_authenticated"
    },
    "/exam/$id/": {
      "filePath": "exam/$id/index.tsx"
    },
    "/placement/$id/": {
      "filePath": "placement/$id/index.tsx"
    },
    "/_auth/forgot-password/": {
      "filePath": "_auth/forgot-password/index.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/login/": {
      "filePath": "_auth/login/index.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/register/": {
      "filePath": "_auth/register/index.lazy.tsx",
      "parent": "/_auth"
    },
    "/_authenticated/profile/": {
      "filePath": "_authenticated/profile/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/transactions/": {
      "filePath": "_authenticated/transactions/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_landing/exams/": {
      "filePath": "_landing/exams/index.lazy.tsx",
      "parent": "/_landing"
    },
    "/exam/end/": {
      "filePath": "exam/end/index.lazy.tsx"
    },
    "/_landing/exams/online/": {
      "filePath": "_landing/exams/online/index.tsx",
      "parent": "/_landing"
    },
    "/exam/admin/$id/": {
      "filePath": "exam/admin/$id/index.tsx"
    },
    "/exam/online/$id/": {
      "filePath": "exam/online/$id/index.tsx"
    },
    "/_authenticated/bookings/$id/": {
      "filePath": "_authenticated/bookings/$id/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/online/$id/": {
      "filePath": "_authenticated/online/$id/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_landing/exams/$id/": {
      "filePath": "_landing/exams/$id/index.lazy.tsx",
      "parent": "/_landing"
    }
  }
}
ROUTE_MANIFEST_END */
